build:
  - source: blocklist/content-farms.txt
    publish: blocklist/content-farms.txt
    data:
      schemes: &content_farms_schemes
        domain-part: &domain_part_scheme_cft
          value: /https?://(?:[\w-]+\.)*(?:{value})(?:\.[\w-]+)*(?=[/?#]|$)/
          escape: regex
          grouping: "|"
          max: 2097152
        domain-path: &domain_path_scheme_cft
          value: /https?://(?:www\.)?(?:{value})(?=[/?#]|$)/
          escape: regex
          grouping: "|"
          max: 2097152
        xuite: &content_farms_scheme
          value: /^https?://(?:(?:m\.)?(?:[bv]log|photo)\.xuite\.net|m\.xuite\.net/blog)/(?:{value})(?=[/?#]|$)/
          escape: regex
          grouping: "|"
          max: 2097152
        udn:
          <<: *content_farms_scheme
          value: /^https?://(?:blog|album)\.udn\.com/(?:mobile/)?(?:{value})(?=[/?#]|$)/
        pchome:
          <<: *content_farms_scheme
          value: /^https?://mypaper\.(?:m\.)?pchome\.com\.tw/(?:{value})(?=[/?#]|$)/

  - source: blocklist/nearly-content-farms.txt
    publish: blocklist/nearly-content-farms.txt

  - source: blocklist/sns-content-farms.txt
    publish: blocklist/sns-content-farms.txt
    data:
      schemes: &sns_content_farms_schemes
        facebook: &sns_content_farms_scheme
          value: /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/(?:pg/)?|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)(?:{value})(?=[/?#]|$)/
          escape: regex
          grouping: "|"
          max: 2097152
        facebook-num:
          <<: *sns_content_farms_scheme
          value: /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/(?:pg/)?|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)(?:[^?#]+/)?(?:[^/?#]+-)?(?:{value})(?=[/?#]|$)/
        facebook-group:
          <<: *sns_content_farms_scheme
          value: /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)groups/(?:{value})(?=[/?#]|$)/
        twitter:
          <<: *sns_content_farms_scheme
          value: /^https?://(?:\w+\.)?twitter\.com/(?:{value})(?=[/?#]|$)/
        youtube-channel:
          <<: *sns_content_farms_scheme
          value: /^https?://(?:\w+\.)?youtube\.com/channel/(?:{value})(?=[/?#]|$)/
        youtube-user:
          <<: *sns_content_farms_scheme
          value: /^https?://(?:\w+\.)?youtube\.com/user/(?:{value})(?=[/?#]|$)/
        instagram:
          <<: *sns_content_farms_scheme
          value: /^https?://(?:www\.)?instagram\.com/(?:{value})(?=[/?#]|$)/
        pinterest:
          <<: *sns_content_farms_scheme
          value: /^https?://(?:www\.)?pinterest(?:\.[a-z]+)+/(?:{value})(?=[/?#]|$)/
        plurk:
          <<: *sns_content_farms_scheme
          value: /^https?://(?:www\.)?plurk\.com/(?:m/p/)?(?:{value})(?=[/?#]|$)/
        line-page:
          <<: *sns_content_farms_scheme
          value: /^https?://page\.line\.me/(?:{value})(?=[/?#]|$)/
        line-timeline:
          <<: *sns_content_farms_scheme
          value: /^https?://timeline\.line\.me/(?:\w+?)/(?:{value})(?=[/?#]|$)/

  - source: blocklist/fake-news.txt
    publish: blocklist/fake-news.txt
    data:
      schemes:
        domain-part: *domain_part_scheme_cft
        domain-path: *domain_path_scheme_cft

  - source: blocklist/scam-sites.txt
    publish: blocklist/scam-sites.txt

  - source: blocklist/content-farms.txt
    publish: blocklist-hosts/content-farms.txt
    type: hosts
    data:
      Title: Content Farm Filters
      Description: Filter for general content farms, mostly in Chinese.
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-hosts/content-farms.txt
      processors:
        - type: domain
          pattern: blogspot\.\*$
          replacement: blogspot.com

  - source: blocklist/nearly-content-farms.txt
    publish: blocklist-hosts/nearly-content-farms.txt
    type: hosts
    data:
      Title: Nearly Content Farm Filters
      Description: Filter for content-farm-like sites, mostly in Chinese.
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-hosts/nearly-content-farms.txt

  - source: blocklist/fake-news.txt
    publish: blocklist-hosts/fake-news.txt
    type: hosts
    data:
      Title: Fake News Filters
      Description: Filter for fake news sites. (for reference)
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-hosts/fake-news.txt

  - source: blocklist/scam-sites.txt
    publish: blocklist-hosts/scam-sites.txt
    type: hosts
    data:
      Title: Scam Sites Filters
      Description: Filter for scam sites. (for reference)
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-hosts/scam-sites.txt

  - source: blocklist/content-farms.txt
    publish: blocklist-ubo/content-farms.txt
    type: ubo
    data:
      Title: Content Farm Filters
      Description: Filter for general content farms, mostly in Chinese.
      Expires: 3 days
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-ubo/content-farms.txt
      schemes:
        <<: *content_farms_schemes
        domain-part: &domain_part_scheme_ubo
          value: "||{value}^"
          mode: raw
        domain-path: &domain_path_scheme_ubo
          value: "||{value}^"
          mode: raw

  - source: blocklist/nearly-content-farms.txt
    publish: blocklist-ubo/nearly-content-farms.txt
    type: ubo
    data:
      Title: Nearly Content Farm Filters
      Description: Filter for content-farm-like sites, mostly in Chinese.
      Expires: 3 days
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-ubo/nearly-content-farms.txt

  - source: blocklist/sns-content-farms.txt
    publish: blocklist-ubo/sns-content-farms.txt
    type: ubo
    data:
      Title: SNS Content Farm Filters
      Description: Filter for content-farm related social media, mostly in Chinese.
      Expires: 3 days
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-ubo/sns-content-farms.txt
      schemes:
        <<: *sns_content_farms_schemes

  - source: blocklist/fake-news.txt
    publish: blocklist-ubo/fake-news.txt
    type: ubo
    data:
      Title: Fake News Filters
      Description: Filter for fake news sites. (for reference)
      Expires: 3 days
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-ubo/fake-news.txt
      schemes:
        domain-part: *domain_part_scheme_ubo
        domain-path: *domain_path_scheme_ubo

  - source: blocklist/scam-sites.txt
    publish: blocklist-ubo/scam-sites.txt
    type: ubo
    data:
      Title: Scam Sites Filters
      Description: Filter for scam sites. (for reference)
      Expires: 3 days
      Homepage: https://github.com/danny0838/content-farm-terminator/tree/gh-pages
      Licence: MIT License
      Source: https://github.com/danny0838/content-farm-terminator/blob/gh-pages/files/blocklist-ubo/scam-sites.txt
