auto_tasks:
  # aggregate sources and build all
  default:
    - action: aggregate
    - action: uniquify
      kwargs:
        files:
          - src/blocklist/not-content-farms.txt
          - src/blocklist/content-farms.txt
        auto_fix_excludes:
          - src/blocklist/not-content-farms.txt
        cross_files: true
        auto_fix: true
    - action: uniquify
      kwargs:
        files:
          - src/blocklist/not-content-farms.txt
          - src/blocklist/bad-cloners.txt
        auto_fix_excludes:
          - src/blocklist/not-content-farms.txt
        cross_files: true
        auto_fix: true
    - action: lint
      kwargs:
        files:
          - src/blocklist/content-farms.txt
          - src/blocklist/bad-cloners.txt
        auto_fix: true
        sort_rules: true
        remove_empty: true
    - action: build

  # lint all general blacklists
  lint:
    - action: lint
      kwargs:
        files:
          - src/blocklist/not-content-farms.txt
          - src/blocklist/content-farms.txt
          - src/blocklist/nearly-content-farms.txt
          - src/blocklist/sns-content-farms.txt
        auto_fix: true
        sort_rules: true

  # uniquify all general blacklists
  uniquify:
    - action: uniquify
      kwargs:
        files:
          - src/blocklist/not-content-farms.txt
        advanced: true
        auto_fix: true
    - action: uniquify
      kwargs:
        files:
          - src/blocklist/not-content-farms.txt
          - src/blocklist/content-farms.txt
          - src/blocklist/nearly-content-farms.txt
          - src/blocklist/sns-content-farms.txt
        advanced: true
        cross_files: true
        auto_fix_excludes:
          - src/blocklist/not-content-farms.txt
        auto_fix: true

aggregate:
  - source:
      - url: https://raw.githubusercontent.com/mxt305/smashXxcnxx/main/filters/xxcnxx-list.json
        type: domains_json
      - url: https://raw.githubusercontent.com/wdmpa/content-farm-list/main/domains/spam/g.penzai.com.txt
        type: ublacklist
    dest: src/blocklist/content-farms.txt
  - source:
      - url: https://raw.githubusercontent.com/arosh/ublacklist-stackoverflow-translation/master/uBlacklist.txt
        type: ublacklist
      - url: https://raw.githubusercontent.com/arosh/ublacklist-github-translation/master/uBlacklist.txt
        type: ublacklist
      - url: https://raw.githubusercontent.com/wdmpa/content-farm-list/main/domains/machine-translated/stackoverflow.txt
        type: ublacklist
    dest: src/blocklist/bad-cloners.txt

build:
  - source: src/blocklist/content-farms.txt
    publish: docs/files/blocklist/content-farms.txt
    data:
      schemes: &content_farms_schemes
        xuite: &grouping_regex_scheme
          value: /^https?://(?:(?:m\.)?(?:[bv]log|photo)\.xuite\.net|m\.xuite\.net/blog)/(?:{value})(?=[/?#]|$)/
          escape: regex
          grouping: "|"
          max: 2097152
        udn:
          <<: *grouping_regex_scheme
          value: /^https?://(?:blog|album)\.udn\.com/(?:mobile/)?(?:{value})(?=[/?#]|$)/
        pchome:
          <<: *grouping_regex_scheme
          value: /^https?://mypaper\.(?:m\.)?pchome\.com\.tw/(?:{value})(?=[/?#]|$)/
        domain-part:
          <<: *grouping_regex_scheme
          value: /https?://(?:[\w-]+\.)*(?:{value})(?:\.[\w-]+)*(?=[:/?#]|$)/
        domain-path:
          <<: *grouping_regex_scheme
          value: /https?://(?:www\.)?(?:{value})(?=[/?#]|$)/

  - source: src/blocklist/nearly-content-farms.txt
    publish: docs/files/blocklist/nearly-content-farms.txt
    data:
      schemes: *content_farms_schemes

  - source: src/blocklist/sns-content-farms.txt
    publish: docs/files/blocklist/sns-content-farms.txt
    data:
      schemes: &sns_content_farms_schemes
        facebook:
          <<: *grouping_regex_scheme
          value: /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/(?:pg/)?|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)(?:{value})(?=[/?#]|$)/
        facebook-num:
          <<: *grouping_regex_scheme
          value: /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/(?:pg/)?|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)(?:[^?#]+/)?(?:[^/?#]+-)?(?:{value})(?=[/?#]|$)/
        facebook-group:
          <<: *grouping_regex_scheme
          value: /^https?://(?:(?:[\w-]+\.)?facebook\.com(?:/|\b[^#]+#!/)|(?:fb|m)\.(?:com|me)/)groups/(?:{value})(?=[/?#]|$)/
        twitter:
          <<: *grouping_regex_scheme
          value: /^https?://(?:\w+\.)?twitter\.com/(?:{value})(?=[/?#]|$)/
        youtube-channel:
          <<: *grouping_regex_scheme
          value: /^https?://(?:\w+\.)?youtube\.com/channel/(?:{value})(?=[/?#]|$)/
        youtube-user:
          <<: *grouping_regex_scheme
          value: /^https?://(?:\w+\.)?youtube\.com/user/(?:{value})(?=[/?#]|$)/
        instagram:
          <<: *grouping_regex_scheme
          value: /^https?://(?:www\.)?instagram\.com/(?:{value})(?=[/?#]|$)/
        pinterest:
          <<: *grouping_regex_scheme
          value: /^https?://(?:www\.)?pinterest(?:\.[a-z]+)+/(?:{value})(?=[/?#]|$)/
        plurk:
          <<: *grouping_regex_scheme
          value: /^https?://(?:www\.)?plurk\.com/(?:m/p/)?(?:{value})(?=[/?#]|$)/
        line-page:
          <<: *grouping_regex_scheme
          value: /^https?://page\.line\.me/(?:{value})(?=[/?#]|$)/
        line-timeline:
          <<: *grouping_regex_scheme
          value: /^https?://timeline\.line\.me/(?:\w+?)/(?:{value})(?=[/?#]|$)/
        haokan-author:
          <<: *grouping_regex_scheme
          value: /https?://(?:haokan|sv)\.baidu\.com/author/(?:{value})(?=[/?#]|$)/

  - source: src/blocklist/bad-cloners.txt
    publish: docs/files/blocklist/bad-cloners.txt
    data:
      schemes: *content_farms_schemes

  - source: src/blocklist/fake-news.txt
    publish: docs/files/blocklist/fake-news.txt
    data:
      schemes: *content_farms_schemes

  - source: src/blocklist/scam-sites.txt
    publish: docs/files/blocklist/scam-sites.txt
    data:
      schemes: *content_farms_schemes

  - source: src/blocklist/content-farms.txt
    publish: docs/files/blocklist-hosts/content-farms.txt
    type: hosts
    data:
      headers: |
        Title: Content Farm Filters
        Description: Filter for general content farms, mostly in Chinese.
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-hosts/content-farms.txt
      processors:
        - type: domain
          pattern: blogspot\.\*$
          replacement: blogspot.com

  - source: src/blocklist/nearly-content-farms.txt
    publish: docs/files/blocklist-hosts/nearly-content-farms.txt
    type: hosts
    data:
      headers: |
        Title: Nearly Content Farm Filters
        Description: Filter for content-farm-like sites, mostly in Chinese.
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-hosts/nearly-content-farms.txt

  - source: src/blocklist/bad-cloners.txt
    publish: docs/files/blocklist-hosts/bad-cloners.txt
    type: hosts
    data:
      headers: |
        Title: Bad Cloners
        Description: Filter for bad clone sites.
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-hosts/bad-cloners.txt

  - source: src/blocklist/fake-news.txt
    publish: docs/files/blocklist-hosts/fake-news.txt
    type: hosts
    data:
      headers: |
        Title: Fake News Filters
        Description: Filter for fake news sites. (for reference)
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-hosts/fake-news.txt

  - source: src/blocklist/scam-sites.txt
    publish: docs/files/blocklist-hosts/scam-sites.txt
    type: hosts
    data:
      headers: |
        Title: Scam Sites Filters
        Description: Filter for scam sites. (for reference)
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-hosts/scam-sites.txt

  - source: src/blocklist/content-farms.txt
    publish: docs/files/blocklist-ubo/content-farms.txt
    type: ubo
    data:
      headers: |
        Title: Content Farm Filters
        Description: Filter for general content farms, mostly in Chinese.
        Expires: 3 days
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ubo/content-farms.txt
      processors: &content_farms_processors_ubo
        - type: domain
          pattern: ^\*\.([\w.-]+)$
          replacement: domain-suffix:\1
      schemes: &content_farms_schemes_ubo
        <<: *content_farms_schemes
        domain-part:
          value: "||{value}^\n||{value}.*^$document"
          mode: raw
        domain-path:
          value: "||{value}^$document"
          mode: raw
        domain-suffix:
          <<: *grouping_regex_scheme
          value: /https?://(?:www\.|(?!www\.))[\w.-]+\.(?:{value})(?=[:/?#]|$)/

  - source: src/blocklist/nearly-content-farms.txt
    publish: docs/files/blocklist-ubo/nearly-content-farms.txt
    type: ubo
    data:
      headers: |
        Title: Nearly Content Farm Filters
        Description: Filter for content-farm-like sites, mostly in Chinese.
        Expires: 3 days
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ubo/nearly-content-farms.txt
      processors: *content_farms_processors_ubo
      schemes: *content_farms_schemes_ubo

  - source: src/blocklist/sns-content-farms.txt
    publish: docs/files/blocklist-ubo/sns-content-farms.txt
    type: ubo
    data:
      headers: |
        Title: SNS Content Farm Filters
        Description: Filter for content-farm related social media, mostly in Chinese.
        Expires: 3 days
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ubo/sns-content-farms.txt
      schemes:
        <<: *sns_content_farms_schemes

  - source: src/blocklist/bad-cloners.txt
    publish: docs/files/blocklist-ubo/bad-cloners.txt
    type: ubo
    data:
      headers: |
        Title: Bad Cloners
        Description: Filter for bad clone sites.
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ubo/bad-cloners.txt
      processors: *content_farms_processors_ubo
      schemes: *content_farms_schemes_ubo

  - source: src/blocklist/fake-news.txt
    publish: docs/files/blocklist-ubo/fake-news.txt
    type: ubo
    data:
      headers: |
        Title: Fake News Filters
        Description: Filter for fake news sites. (for reference)
        Expires: 3 days
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ubo/fake-news.txt
      processors: *content_farms_processors_ubo
      schemes: *content_farms_schemes_ubo

  - source: src/blocklist/scam-sites.txt
    publish: docs/files/blocklist-ubo/scam-sites.txt
    type: ubo
    data:
      headers: |
        Title: Scam Sites Filters
        Description: Filter for scam sites. (for reference)
        Expires: 3 days
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ubo/scam-sites.txt
      processors: *content_farms_processors_ubo
      schemes: *content_farms_schemes_ubo

  - source: src/blocklist/content-farms.txt
    publish: docs/files/blocklist-ublacklist/content-farms.txt
    type: ublacklist
    data:
      headers: |
        Title: Content Farm Filters
        Description: Filter for general content farms, mostly in Chinese.
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ublacklist/content-farms.txt
      processors: &content_farms_processors_ublacklist
        - type: domain
          pattern: ^\*\.([\w.-]+)$
          replacement: domain-suffix:\1
        - type: domain
          pattern: ^([\w-]+)\.blogspot\.\*$
          replacement: blogspot:\1
      schemes: &content_farms_schemes_ublacklist
        <<: *content_farms_schemes
        domain-part:
          <<: *grouping_regex_scheme
          value: /https?://(?:[\w-]+\.)*(?:{value})(?:\.[\w-]+)*(?=[:\/?#]|$)/
        domain-path:
          value: "*://*.{value}\n*://*.{value}/*"
          mode: raw
        domain-suffix:
          <<: *grouping_regex_scheme
          value: /https?://(?:www\.|(?!www\.))[\w.-]+\.(?:{value})(?=[:/?#]|$)/
        blogspot:
          <<: *grouping_regex_scheme
          value: /https?://(?:[\w-]+\.)*(?:{value})\.blogspot\.(?:[\w.-]+)(?=[:\/?#]|$)/

  - source: src/blocklist/nearly-content-farms.txt
    publish: docs/files/blocklist-ublacklist/nearly-content-farms.txt
    type: ublacklist
    data:
      headers: |
        Title: Nearly Content Farm Filters
        Description: Filter for content-farm-like sites, mostly in Chinese.
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ublacklist/nearly-content-farms.txt
      processors: *content_farms_processors_ublacklist
      schemes: *content_farms_schemes_ublacklist

  - source: src/blocklist/bad-cloners.txt
    publish: docs/files/blocklist-ublacklist/bad-cloners.txt
    type: ublacklist
    data:
      headers: |
        Title: Bad Cloners
        Description: Filter for bad clone sites.
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ublacklist/bad-cloners.txt
      processors: *content_farms_processors_ublacklist
      schemes: *content_farms_schemes_ublacklist

  - source: src/blocklist/fake-news.txt
    publish: docs/files/blocklist-ublacklist/fake-news.txt
    type: ublacklist
    data:
      headers: |
        Title: Fake News Filters
        Description: Filter for fake news sites. (for reference)
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ublacklist/fake-news.txt
      processors: *content_farms_processors_ublacklist
      schemes: *content_farms_schemes_ublacklist

  - source: src/blocklist/scam-sites.txt
    publish: docs/files/blocklist-ublacklist/scam-sites.txt
    type: ublacklist
    data:
      headers: |
        Title: Scam Sites Filters
        Description: Filter for scam sites. (for reference)
        Last modified: {now}
        Homepage: https://danny0838.github.io/content-farm-terminator/
        Licence: MIT License
        Source: https://danny0838.github.io/content-farm-terminator/files/blocklist-ublacklist/scam-sites.txt
      processors: *content_farms_processors_ublacklist
      schemes: *content_farms_schemes_ublacklist

  - source: src/url-transform-rules/content-farms.txt
    publish: docs/files/url-transform-rules/content-farms.txt
    type: copy

  - source: src/url-transform-rules/sns-content-farms.txt
    publish: docs/files/url-transform-rules/sns-content-farms.txt
    type: copy
