name: Aggregate sources and rebuild

on:
  workflow_dispatch:
  schedule:
    # 19:42 UTC every Sunday
    - cron: "42 19 * * 0"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    # Add explicit permissions for pushing
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          fetch-depth: 1

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install -r scripts/requirements.txt

      - name: Aggregate and build
        run: |
          python scripts/build.py auto aggregate &&
          python scripts/build.py auto

      - name: Commit files
        run: |
          git config user.name 'GitHub Action' &&
          git config user.email 'actions@github.com' &&
          git add -u . &&
          git commit -m "cd: auto build at $(TZ=UTC date +'%F'T'%T'Z)" &&
          git push --force-with-lease
