name: Publish extension

on:
  workflow_dispatch:
    inputs:
      create_tag:
        description: Create tag
        type: boolean
        default: true
      upload_chrome:
        description: Upload Chrome
        type: boolean
        default: true
      upload_edge:
        description: Upload Edge
        type: boolean
        default: true
      upload_fx:
        description: Upload Firefox
        type: boolean
        default: true

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    env:
      CREATE_TAG: ${{ github.event.inputs.create_tag }}
      UPLOAD_CHROME: ${{ github.event.inputs.upload_chrome }}
      UPLOAD_EDGE: ${{ github.event.inputs.upload_edge }}
      UPLOAD_FX: ${{ github.event.inputs.upload_fx }}

    # Add explicit permissions for tag/release
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure and verify
        run: |
          VERSION=$(jq -r '.version' './src/manifest.json')
          VERSION_FX=$(jq -r '.version' './src/manifest-firefox.json')
          if [ "$VERSION" != "$VERSION_FX" ]; then
            echo "❌ Mismatching manifest versions"
            exit 1
          fi

          EXPECTED_LINE="## 終結內容農場 v$VERSION"
          if ! grep -Fxq "$EXPECTED_LINE" RELEASES.md; then
            echo "❌ Missing expected line in `RELEASES.md`: $EXPECTED_LINE"
            exit 1
          fi

          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "TAG_NAME=$VERSION" >> $GITHUB_ENV
          echo "EXT_PATH_ZIP=dist/content-farm-terminator.zip" >> $GITHUB_ENV
          echo "EXT_PATH_XPI=dist/content-farm-terminator.xpi" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm install

      - name: Verify no code issue
        run: npm run lint

      - name: Build extension
        run: build/pack.sh

      - name: Create Git Tag
        if: ${{ env.CREATE_TAG == 'true' }}
        run: |
          git tag --force ${{ env.TAG_NAME }}
          git push origin ${{ env.TAG_NAME }}

      - name: Upload to Chrome Web Store
        if: ${{ env.UPLOAD_CHROME == 'true' }}
        uses: mnao305/chrome-extension-upload@v5.0.0
        with:
          file-path: ${{ env.EXT_PATH_ZIP }}
          extension-id: ${{ vars.CHROME_EXTENSION_ID }}

          # https://github.com/fregante/chrome-webstore-upload-keys
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}

      - name: Upload to Microsoft Edge Add-ons
        if: ${{ env.UPLOAD_EDGE == 'true' }}
        uses: wdzeng/edge-addon@v2
        with:
          zip-path: ${{ env.EXT_PATH_ZIP }}
          product-id: ${{ vars.EDGE_PRODUCT_ID }}
          client-id: ${{ secrets.EDGE_CLIENT_ID }}
          api-key: ${{ secrets.EDGE_API_KEY }}

      - name: Upload to Firefox Add-ons
        if: ${{ env.UPLOAD_FX == 'true' }}
        uses: kewisch/action-web-ext@v1
        with:
          cmd: sign
          channel: listed
          source: ${{ env.EXT_PATH_XPI }}
          artifacts: dist
          apiKey: ${{ secrets.FIREFOX_API_KEY }}
          apiSecret: ${{ secrets.FIREFOX_API_SECRET }}
